# Generated by Django 5.2.3 on 2026-02-09 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='previous_work',
        ),
        migrations.AddField(
            model_name='profile',
            name='projects',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
