# Generated by Django 5.2.3 on 2026-02-09 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0003_remove_profile_school_profile_github_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='certifications',
            field=models.TextField(default='', max_length=2000),
        ),
    ]
